name: ci
on:
  push:
  pull_request:
    types: [opened, reopened]
jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.3.7
          bundler-cache: true
      - run: sudo apt-get install -y libsodium-dev
      - run: bundle exec rake
